(window.webpackJsonp=window.webpackJsonp||[]).push([[27],{509:function(e,t,s){"use strict";s.r(t);var a=s(2),o=Object(a.a)({},(function(){var e=this,t=e.$createElement,s=e._self._c||t;return s("ContentSlotsDistributor",{attrs:{"slot-key":e.$parent.slotKey}},[s("h1",{attrs:{id:"day-17"}},[s("a",{staticClass:"header-anchor",attrs:{href:"#day-17"}},[e._v("#")]),e._v(" Day 17")]),e._v(" "),s("p",[s("strong",[e._v("01/05/2021")])]),e._v(" "),s("h2",{attrs:{id:"what-are-the-three-states-of-a-promise"}},[s("a",{staticClass:"header-anchor",attrs:{href:"#what-are-the-three-states-of-a-promise"}},[e._v("#")]),e._v(" What are the three states of a Promise?")]),e._v(" "),s("p",[e._v("The three states of a promis are first: Pending, second: Resolved, and third: Rejected. The Pending state is the time that the promise exists before it succeeds or fails. The resolved state is what happens when a promise completes and clears or resolved. Finally the Rejected state of a promise refers to when a Promise fails or gets rejected.")]),e._v(" "),s("h2",{attrs:{id:"how-do-promises-seek-to-resolve-the-issues-of-callback-hell"}},[s("a",{staticClass:"header-anchor",attrs:{href:"#how-do-promises-seek-to-resolve-the-issues-of-callback-hell"}},[e._v("#")]),e._v(" How do promises seek to resolve the issues of 'Callback Hell'?")]),e._v(" "),s("p",[e._v("Callbacks themselves are susceptable to becoming a source of Callback Hell. If a developer puts multiple callbacks nested within one another, that is a form of Callback Hell. Promises can resolve this issue through chaining. Callbacks can be attached to the end of a line of code instead of being passed through like a function. This helps the code avoid becoming a pyramid of doom so to say. This keeps the codes readability.")]),e._v(" "),s("h2",{attrs:{id:"what-is-the-difference-between-then-and-catch"}},[s("a",{staticClass:"header-anchor",attrs:{href:"#what-is-the-difference-between-then-and-catch"}},[e._v("#")]),e._v(" What is the difference between .then() and .catch()?")]),e._v(" "),s("p",[e._v("The difference between .then() and .catch() is fairly simple. Then is used for whenever a promise is resolved. Catch is used for when a promise is rejected. Then allows for us to decide after it runs what to do with the resolved promise. If the promise fails, we use the Catch method. Catch can be attached directly after Then. If the promise gets resolved there can be an outcome, and with the Catch method attached on the end if it fails another outcome can be achieved.")]),e._v(" "),s("h2",{attrs:{id:"afternoon-project-link"}},[s("a",{staticClass:"header-anchor",attrs:{href:"#afternoon-project-link"}},[e._v("#")]),e._v(" Afternoon Project Link:")]),e._v(" "),s("p",[e._v("https://steffenlarson.github.io/winter2020-api-gregslist/")])])}),[],!1,null,null,null);t.default=o.exports}}]);